version: "3.8"
services:
  elasticsearch:
    build: ./
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  elasticsearch:
    driver: local
